function skillsMember() {
    return {
        title: 'Skills',
        skills: [
            'HTML',
            'CSS',
            'JavaScript',
            'ReactJS',
            'NodeJS',
            'ExpressJS',
            'MongoDB',
            'Python',
            'Java',
            'C',
            'C++',
            'Git',
            'GitHub',
            'Visual Studio Code',
            'Atom',
            'Linux',
            'Windows',
            'MacOS',
            'Microsoft Office',
            'Figma',
            'Adobe XD',
            'Adobe Photoshop',
            'Adobe Illustrator',
            'Adobe Premiere Pro',
            'Adobe After Effects',
            'Sony Vegas Pro',
            'Ableton Live',
            'FL Studio',
            'Pro Tools',
            'Audacity',
            'Microsoft Azure',
            'Amazon Web Services',
            'Google Cloud Platform',
            'Firebase',
            'Heroku',
            'Netlify',
            'Vercel',
            'Docker',
            'Kubernetes',
            'Jenkins',
            'Travis CI',
            'CircleCI',
            'GitHub Actions',
            'Slack',
            'Microsoft Teams',
            'Zoom',
            'Google Meet',
            'Discord',
            'Telegram',
            'WhatsApp',
            'Signal',
            'Facebook',
            'Instagram',
            'Twitter',
            'LinkedIn',
            'Snapchat',
            'TikTok',
            'Pinterest',
            'Reddit',
            'YouTube',
            'Twitch',
            'Spotify',
            'Apple Music',
            'SoundCloud',
            'Bandcamp',
            'Patreon',
            'Kickstarter',
            'Indiegogo',
            'GoFundMe',
            'PayPal',
            'Stripe',
            'Square',
            'Shopify',
            'WooCommerce',
            'Magento',
            'BigCommerce',
            'Squarespace',
            'Wix',
            'WordPress',
            'Joomla',
            'Drupal',
            'Ghost',
            'Blogger',
            'Medium',
            'Dev.to',
            'Hashnode',
            'Netlify CMS',
            'Strapi',
            'Contentful',
            'WordPress REST API',
            'GraphQL',
            'REST API',
            'JSON',
            'XML',
            'Markdown',
            'YAML',
            'CSV',
            'SQL',
            'NoSQL',
            'MongoDB Atlas',
            '